const questions = [
    // Niveau 1 : Facile
    { question: "Quel chef gaulois a affronté Jules César à Alésia ?", answers: ["Astérix", "Vercingétorix", "Attila"], correct: 1 },
    { question: "Quel roi des Francs s'est fait baptiser à Reims vers 496 ?", answers: ["Clovis", "Dagobert", "Charlemagne"], correct: 0 },
    { question: "Quel empereur a été couronné le jour de Noël en l'an 800 ?", answers: ["Saint Louis", "Charlemagne", "François Ier"], correct: 1 },
    { question: "Quelle héroïne a délivré Orléans des Anglais en 1429 ?", answers: ["Jeanne d'Arc", "Catherine de Médicis", "Marie Curie"], correct: 0 },
    { question: "Quel roi de France a remporté la bataille de Marignan en 1515 ?", answers: ["Louis XIV", "François Ier", "Henri IV"], correct: 1 },
    { question: "Quel roi a signé l'Édit de Nantes en 1598 ?", answers: ["Henri IV", "Louis XIII", "Louis XIV"], correct: 0 },
    { question: "Quel monarque était surnommé le « Roi-Soleil » ?", answers: ["Louis XV", "Louis XIV", "Louis XVI"], correct: 1 },
    { question: "Quel château a été la résidence principale de Louis XIV ?", answers: ["Le château de Chambord", "Le château de Versailles", "Le château de Fontainebleau"], correct: 1 },
    { question: "En quelle année la prise de la Bastille a-t-elle eu lieu ?", answers: ["1789", "1799", "1804"], correct: 0 },
    { question: "Quelle reine de France, épouse de Louis XVI, a été guillotinée en 1793 ?", answers: ["Anne d'Autriche", "Marie-Antoinette", "Marie de Médicis"], correct: 1 },
    { question: "Quel général s'est sacré Empereur des Français en 1804 ?", answers: ["Napoléon Bonaparte", "Le général de Gaulle", "Le maréchal Pétain"], correct: 0 },
    { question: "Dans quelle célèbre bataille de 1815 Napoléon Ier a-t-il été définitivement battu ?", answers: ["Austerlitz", "Waterloo", "Valmy"], correct: 1 },
    { question: "Quel drapeau est devenu le symbole officiel de la République française ?", answers: ["Le drapeau blanc et or", "Le drapeau bleu, blanc, rouge", "Le drapeau rouge et noir"], correct: 1 },
    { question: "Quelle grande guerre s'est déroulée de 1914 à 1918 ?", answers: ["La guerre de Cent Ans", "La Première Guerre mondiale", "La Seconde Guerre mondiale"], correct: 1 },
    { question: "Quelle célèbre bataille sanglante a eu lieu dans la Meuse en 1916 ?", answers: ["La bataille de la Somme", "La bataille de Verdun", "La bataille de la Marne"], correct: 1 },
    { question: "Quel général a lancé l'Appel du 18 juin 1940 depuis Londres ?", answers: ["Charles de Gaulle", "Philippe Pétain", "Jean de Lattre de Tassigny"], correct: 0 },
    { question: "En quelle année a eu lieu le débarquement allié en Normandie ?", answers: ["1940", "1944", "1948"], correct: 1 },
    { question: "En quelle année les femmes ont-elles obtenu le droit de vote en France ?", answers: ["1936", "1944", "1968"], correct: 1 },
    { question: "Quelle République est la forme actuelle du gouvernement français (instaurée en 1958) ?", answers: ["La IIIe République", "La IVe République", "La Ve République"], correct: 2 },
    { question: "Quel événement social et étudiant majeur a secoué la France au printemps 1968 ?", answers: ["Le Front populaire", "Mai 68", "La Commune de Paris"], correct: 1 },

    // Niveau 2 : Moyen
    { question: "Quelle bataille navale de 1340 marque le début de la guerre de Cent Ans ?", answers: ["La bataille de l'Écluse", "La bataille de Crécy", "La bataille d'Azincourt"], correct: 0 },
    { question: "Quel roi de France a été fait prisonnier lors de la bataille de Pavia en 1525 ?", answers: ["Charles VIII", "François Ier", "Henri II"], correct: 1 },
    { question: "Quel massacre de protestants s'est déroulé à Paris la nuit du 24 août 1572 ?", answers: ["La Saint-Barthélemy", "La nuit des Barricades", "La conspiration d'Amboise"], correct: 0 },
    { question: "Quel puissant cardinal a servi comme principal ministre sous Louis XIII ?", answers: ["Mazarin", "Richelieu", "Fleury"], correct: 1 },
    { question: "Quelle série de révoltes contre le pouvoir royal a eu lieu sous la minorité de Louis XIV ?", answers: ["La Jacquerie", "La Fronde", "La Ligue"], correct: 1 },
    { question: "Quel ministre des Finances de Louis XIV a fondé la Compagnie des Indes orientales ?", answers: ["Jean-Baptiste Colbert", "Nicolas Fouquet", "Anne Robert Jacques Turgot"], correct: 0 },
    { question: "Quel roi est monté sur le trône après la mort de Louis XIV en 1715 ?", answers: ["Louis XV", "Louis XVI", "Louis-Philippe Ier"], correct: 0 },
    { question: "En quelle année le serment du Jeu de paume a-t-il été prêté ?", answers: ["1789", "1791", "1793"], correct: 0 },
    { question: "Quel révolutionnaire surnommé « l'Incorruptible » a dirigé le Comité de salut public ?", answers: ["Georges Danton", "Maximilien de Robespierre", "Jean-Paul Marat"], correct: 1 },
    { question: "Quel coup d'État a permis à Napoléon Bonaparte de prendre le pouvoir en 1799 ?", answers: ["Le coup d'État du 18 Brumaire", "Le coup d'État du 9 Thermidor", "Le coup d'État du 2 Décembre"], correct: 0 },
    { question: "Quelle victoire napoléonienne de 1805 est aussi connue sous le nom de « bataille des Trois Empereurs » ?", answers: ["Iéna", "Friedland", "Austerlitz"], correct: 2 },
    { question: "Quel roi est placé sur le trône de France lors de la Première Restauration en 1814 ?", answers: ["Charles X", "Louis XVIII", "Louis-Philippe Ier"], correct: 1 },
    { question: "Quelle révolution de trois jours en 1830 a renversé le roi Charles X ?", answers: ["Les Trois Glorieuses", "La Révolution de Février", "La Commune"], correct: 0 },
    { question: "Quel neveu de Napoléon Ier est devenu le premier président de la République française en 1848 ?", answers: ["Napoléon II", "Louis-Napoléon Bonaparte", "Eugène de Beauharnais"], correct: 1 },
    { question: "Quelle guerre a provoqué la chute du Second Empire en 1870 ?", answers: ["La guerre franco-prussienne", "La guerre de Crimée", "La campagne d'Italie"], correct: 0 },
    { question: "Quel accord signé en 1904 a scellé le rapprochement diplomatique entre la France et le Royaume-Uni ?", answers: ["La Sainte-Alliance", "L'Entente cordiale", "Le traité de Versailles"], correct: 1 },
    { question: "Quel homme politique surnommé « Le Tigre » a dirigé le gouvernement français à la fin de la Première Guerre mondiale ?", answers: ["Jean Jaurès", "Georges Clemenceau", "Aristide Briand"], correct: 1 },
    { question: "Quelle coalition de gauche a remporté les élections législatives françaises en 1936 ?", answers: ["Le Cartel des gauches", "Le Front populaire", "L'Union sacrée"], correct: 1 },
    { question: "Quel préfet a unifié la Résistance française en créant le Conseil national de la Résistance (CNR) ?", answers: ["Jean Moulin", "Pierre Brossolette", "Emmanuel d'Astier de La Vigerie"], correct: 0 },
    { question: "Quel traité signé en 1957 a fondé la Communauté économique européenne (CEE) avec la France ?", answers: ["Le traité de Paris", "Le traité de Rome", "Le traité de Maastricht"], correct: 1 },

    // Niveau 3 : Difficile
    { question: "Quel roi carolingien, dit « le Simple », a cédé la Normandie au chef viking Rollon au traité de Saint-Clair-sur-Epte en 911 ?", answers: ["Charles III", "Charles le Chauve", "Louis IV"], correct: 0 },
    { question: "Quel souverain a remporté la bataille de Bouvines en 1214 contre une coalition européenne ?", answers: ["Philippe Auguste", "Louis VII", "Philippe le Bel"], correct: 0 },
    { question: "Quelle ordonnance signée par François Ier en 1539 a imposé l'usage du français dans les actes officiels ?", answers: ["L'ordonnance de Villers-Cotterêts", "L'ordonnance de Moulins", "L'ordonnance de Blois"], correct: 0 },
    { question: "Quel traité de 1659 a mis fin à la guerre entre la France et l'Espagne et a scellé le mariage de Louis XIV avec Marie-Thérèse d'Autriche ?", answers: ["Le traité de Westphalie", "Le traité des Pyrénées", "Le traité de Nimègue"], correct: 1 },
    { question: "Quelle grande révolte paysanne s'est déroulée dans les Cévennes au début du XVIIIe siècle à la suite de la révocation de l'Édit de Nantes ?", answers: ["La révolte des Bonnets rouges", "La guerre des Camisards", "La révolte des Va-Nu-Pieds"], correct: 1 },
    { question: "Quel traité a mis fin à la guerre de Sept Ans en 1763, faisant perdre à la France la majeure partie de son premier empire colonial ?", answers: ["Le traité de Paris", "Le traité d'Utrecht", "Le traité d'Aix-la-Chapelle"], correct: 0 },
    { question: "Quel ministre des Finances de Louis XVI a publié le « Compte rendu au Roi » en 1781 ?", answers: ["Calonne", "Necker", "Brienne"], correct: 1 },
    { question: "Quel événement du 9 Thermidor an II (27 juillet 1794) a marqué la fin de la Terreur ?", answers: ["L'exécution de Danton", "La chute de Robespierre", "L'arrestation de Marat"], correct: 1 },
    { question: "Quelle bataille de 1809 a vu la victoire difficile de Napoléon contre les Autrichiens au prix de lourdes pertes ?", answers: ["Wagram", "Eylau", "Essling"], correct: 0 },
    { question: "Quel traité signé en 1807 entre Napoléon Ier et le tsar Alexandre Ier a divisé l'Europe en zones d'influence ?", answers: ["Le traité de Tilsit", "Le traité de Pressbourg", "Le traité de Schönbrunn"], correct: 0 },
    { question: "Quel roi a été renversé par la Révolution de 1848, entraînant la proclamation de la Deuxième République ?", answers: ["Charles X", "Louis-Philippe Ier", "Louis XVIII"], correct: 1 },
    { question: "Quel soulèvement insurrectionnel parisien s'est déroulé de mars à mai 1871 ?", answers: ["La Commune de Paris", "La révolte des Canuts", "Les journées de Juin"], correct: 0 },
    { question: "Quel officier français de confession juive a été victime d'une grave erreur judiciaire à la fin du XIXe siècle ?", answers: ["Ferdinand Walsin Esterhazy", "Alfred Dreyfus", "Georges Picquart"], correct: 1 },
    { question: "Quelle loi majeure instaurant la séparation des Églises et de l'État a été promulguée en France ?", answers: ["La loi du 9 décembre 1905", "La loi Guizot de 1833", "La loi Ferry de 1881"], correct: 0 },
    { question: "Quel navire de guerre français a été sabordé à Toulon le 27 novembre 1942 pour éviter sa capture par les Allemands ?", answers: ["Le Dunkerque", "Le Richelieu", "La flotte entière (dont le Strasbourg)"], correct: 2 },
    { question: "Quel accord a mis fin à la guerre d'Algérie en mars 1962 ?", answers: ["Les accords d'Évian", "Les accords de Genève", "Les accords de Paris"], correct: 0 },
    { question: "Quel homme politique a été le premier Premier ministre de François Mitterrand en 1981 ?", answers: ["Laurent Fabius", "Pierre Mauroy", "Michel Rocard"], correct: 1 },
    { question: "Quel traité européen ratifié de justesse par les Français par référendum en 1992 a créé l'Union européenne ?", answers: ["Le traité de Maastricht", "Le traité d'Amsterdam", "Le traité de Nice"], correct: 0 },
    { question: "Quel président de la République a dissous l'Assemblée nationale en 1997, entraînant une cohabitation avec Lionel Jospin ?", answers: ["Valéry Giscard d'Estaing", "François Mitterrand", "Jacques Chirac"], correct: 2 },
    { question: "En quelle année l'Euro est-il devenu la monnaie fiduciaire (pièces et billets) en circulation en France ?", answers: ["1999", "2002", "2005"], correct: 1 },
];